[package]
name = "stede_hook"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "stede_hook"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
anchor-debug = []
custom-heap = []
custom-panic = []

[dependencies]
anchor-lang = { version = "0.32.1", features = ["init-if-needed"] }
anchor-spl = { version = "0.32.1", features = ["token", "token_2022", "token_2022_extensions"] }
spl-transfer-hook-interface = "0.10.0"
spl-tlv-account-resolution = "0.10.0"
stede_rule_daily_limit = { path = "../stede_rule_daily_limit", features = ["cpi"] }
stede_rule_block_handle = { path = "../stede_rule_block_handle", features = ["cpi"] }
stede_rule_cooloff = { path = "../stede_rule_cooloff", features = ["cpi"] }
stede_rule_new_recipient_delay = { path = "../stede_rule_new_recipient_delay", features = ["cpi"] }
stede_rule_time_window = { path = "../stede_rule_time_window", features = ["cpi"] }
stede_rule_friend_gate = { path = "../stede_rule_friend_gate", features = ["cpi"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }